Refactoring
kyunooh/gaeim pull request #1
Opened 2018-07-15 13:33 UTC by qkraudghgh

1. xmlHttpRequest를 fetch로 변환
2. 코드 가독성 좀 더 좋게 수정
3. css 파일 분리
4. document에 append하는 횟수를 1번으로 수정

테스트 후 머지 바랍니다.

2018-07-15 13:38 UTC, qkraudghgh commented
아 css도 조금 수정했는데 `accounts`를 flex column으로 바꿨고 각 프로필에 padding도 좀 줬습니다.
기존 css 레이아웃이 버그가 있었어요 프로필이 여러개면 프로필이 계단식으로 보임..
아무튼 수정했음

2018-07-16 00:20 UTC, kyunooh requested changes
platform에 thumbnail과 같이 nickname 필드도 예외 처리 부탁드립니다.
+ 스크립트도 js 파일로 빼주세요!

2018-07-16 00:46 UTC, qkraudghgh commented
@kyunooh 여기요

2018-07-16 01:09 UTC, kyunooh commented
LGTM!

2018-07-16 01:09 UTC, merged